# Generated by Django 3.2.4 on 2021-06-30 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDescription',
            fields=[
                ('free_text', models.TextField(max_length=1024, verbose_name='Describe your case')),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('q1_last_relative_left_poland', models.CharField(max_length=128, verbose_name='Name and surname of last know relative that lived in Poland')),
                ('q2_next_destination', models.CharField(max_length=128, verbose_name='Where did this last relative lived afterwards?')),
                ('q3_other_citizenships', models.CharField(max_length=128, verbose_name='Do you hold additional citizenships? If yes, which ones?')),
                ('q4_granfather_army', models.CharField(max_length=128, verbose_name='Did your grandfather served in any army?')),
                ('q5_grandfather_profession', models.CharField(max_length=128, verbose_name='What was your grandfather profession')),
                ('q6_family_in_poland', models.CharField(max_length=128, verbose_name='Any remaining relatives still live in Poland?')),
                ('q7_polish_docs', models.CharField(max_length=128, verbose_name='Please list all related documents that you have')),
                ('q8_addoption', models.CharField(max_length=128, verbose_name='Were you adopted?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='What is your full name, including middle names?')),
                ('surname', models.CharField(max_length=64, verbose_name='Your surname:')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
                ('place_of_birth', models.CharField(max_length=128, verbose_name='Place of birth')),
                ('date_of_mariage', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
                ('place_of_mariage', models.CharField(max_length=128, verbose_name='Place of mariage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('phone', models.CharField(max_length=12, verbose_name='Please provide your phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Please provide your contact email address')),
                ('cbp', models.BooleanField(default=None, verbose_name='Preferred contact by phone?')),
                ('cbe', models.BooleanField(default=None, verbose_name='Preferred contact by email?')),
                ('day', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='DocUpload',
            fields=[
                ('description', models.CharField(max_length=64)),
                ('doc', models.FileField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleParentDetails',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='Mothers name')),
                ('surname', models.CharField(max_length=64, verbose_name='Mothers surname')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
                ('place_of_birth', models.CharField(max_length=128, verbose_name='Place of birth')),
                ('date_of_mariage', models.DateField(verbose_name='Date of mariage (YYYY-MM-DD)')),
                ('place_of_mariage', models.CharField(max_length=128, verbose_name='Place of mariage')),
                ('maiden_name', models.CharField(max_length=128, verbose_name='Your mother maiden name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='MaleParentDetails',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='Fathers name')),
                ('surname', models.CharField(max_length=64, verbose_name='Fathers surname')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
                ('place_of_birth', models.CharField(max_length=128, verbose_name='Place of birth')),
                ('date_of_mariage', models.DateField(verbose_name='Date of mariage (YYYY-MM-DD)')),
                ('place_of_mariage', models.CharField(max_length=128, verbose_name='Place of mariage')),
                ('military_service', models.CharField(max_length=128, verbose_name='Has your father served in army? If yes, then which country?')),
                ('occupation_before_51', models.CharField(max_length=128, verbose_name='What was your father occupation before 1951?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('citizenship', models.BooleanField(default=None, verbose_name='Citizenship acquisition')),
                ('research', models.BooleanField(default=None, verbose_name='Citizenship research')),
                ('grant', models.BooleanField(default=None, verbose_name='Citizenship by grant')),
                ('eligibility', models.BooleanField(default=None, verbose_name='Eligibility check')),
                ('comment', models.TextField(max_length=900, null=True, verbose_name='Any additional comments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='SupportPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup1', models.BooleanField(verbose_name='Barbara')),
                ('sup2', models.BooleanField(verbose_name='Dorota')),
                ('sup3', models.BooleanField(verbose_name='Marta')),
                ('support_person', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
